# Generated by Django 4.2.12 on 2024-05-30 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bgimg",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 30, 20, 23, 21, 200253)
            ),
        ),
    ]
